const UPSTOX_BASE='https://api.upstox.com';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(body));}
function cookies(req){const out={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out;}
async function upstox(path,req){const token=cookies(req).upstox_access_token||process.env.UPSTOX_ANALYTICS_TOKEN;if(!token)throw new Error('UPSTOX_NOT_CONNECTED');const r=await fetch(UPSTOX_BASE+path,{headers:{Accept:'application/json',Authorization:'Bearer '+token}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('Upstox '+r.status);return d;}
const clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const dateIST=(n=0)=>{const d=new Date(Date.now()+5.5*60*60*1000);d.setUTCDate(d.getUTCDate()-n);return d.toISOString().slice(0,10)};
async function resolve(symbol,req){const d=await upstox('/v2/instruments/search?query='+encodeURIComponent(symbol)+'&exchanges=NSE&segments=EQ&page_number=1&records=30',req);const a=Array.isArray(d?.data)?d.data:[];const x=a.find(r=>r.segment==='NSE_EQ'&&clean(r.trading_symbol)===clean(symbol))||a.find(r=>r.segment==='NSE_EQ');return x?{symbol,instrument_key:x.instrument_key,trading_symbol:x.trading_symbol,name:x.name||x.short_name}:null;}
async function candles(key,unit,interval,fromDays,req){const to=dateIST(0),from=dateIST(fromDays);const d=await upstox('/v3/historical-candle/'+encodeURIComponent(key)+'/'+unit+'/'+interval+'/'+to+'/'+from,req);return Array.isArray(d?.data?.candles)?d.data.candles:[];}
function norm(cs){return cs.map(c=>({t:new Date(c[0]).getTime(),o:+c[1],h:+c[2],l:+c[3],c:+c[4],v:+(c[5]||0)})).filter(x=>x.c>0).sort((a,b)=>a.t-b.t);}
function atr(a,n=14){if(a.length<n+1)return null;const tr=a.slice(1).map((x,i)=>Math.max(x.h-x.l,Math.abs(x.h-a[i].c),Math.abs(x.l-a[i].c)));return tr.slice(-n).reduce((s,x)=>s+x,0)/n;}
function analyze(day,mins){if(day.length<30)return{score:0,signal:'WAIT',reason:'Insufficient daily history',setup:'WAIT'};const d=day.at(-1),p=day.slice(-20,-1),high=Math.max(...p.map(x=>x.h)),low=Math.min(...p.map(x=>x.l)),avgv=p.reduce((s,x)=>s+x.v,0)/p.length,a=atr(day)||d.c*.02;let score=0,why=[];if(d.c>high){score+=35;why.push('20D breakout')}else if(d.c>Math.max(...p.slice(-5).map(x=>x.h))){score+=18;why.push('short-term strength')}if(d.c>day.at(-21).c){score+=15;why.push('trend up')}if(d.c<low){score-=35;why.push('20D breakdown')}if(avgv&&d.v>avgv*1.5){score+=d.c>d.o?20:-20;why.push('high volume')}if(mins.length>=12){const m=mins.at(-1),mp=mins.slice(-7,-1),mh=Math.max(...mp.map(x=>x.h));if(m.c>mh){score+=10;why.push('5m confirmation')}}score=Math.max(-100,Math.min(100,score));const signal=score>=60?'BUY':score<=-60?'SELL':'WAIT';const setup=score>=60?(d.c>high?'BREAKOUT':'PULLBACK'):score<=-60?'BREAKDOWN':'WAIT';const entryLow=d.c*.998,entryHigh=d.c*1.004,sl=Math.max(d.c-1.2*a,d.c*.97),risk=Math.max(d.c-sl,.01),t1=d.c+risk*1.5,t2=d.c+risk*2.2,t3=d.c+risk*3;return{score,signal,setup,close:d.c,volume_ratio:avgv?+(d.v/avgv).toFixed(2):null,entry_low:+entryLow.toFixed(2),entry_high:+entryHigh.toFixed(2),sl:+sl.toFixed(2),t1:+t1.toFixed(2),t2:+t2.toFixed(2),t3:+t3.toFixed(2),rr:'1:2.2',atr:+a.toFixed(2),reason:why.join(' + ')||'No A+ confirmation',holding:'2–4 days'};}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{ok:false,error:'GET only'});try{const raw=String(req.query?.symbols||'RELIANCE,SBIN,HDFCBANK,ICICIBANK,INFY,TCS,AXISBANK,TATASTEEL,MARUTI,BHARTIARTL').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean).slice(0,20);const resolved=(await Promise.all(raw.map(s=>resolve(s,req)))).filter(Boolean);const rows=await Promise.all(resolved.map(async x=>{try{const [day5,mins]=await Promise.all([candles(x.instrument_key,'days','1',90,req),candles(x.instrument_key,'minutes','5',7,req)]);return {...x,...analyze(norm(day5),norm(mins)),data_source:'Upstox historical',candle_count:day5.length};}catch(e){return {...x,score:0,signal:'WAIT',setup:'WAIT',reason:e.message||'Data unavailable',data_source:'Unavailable',candle_count:0};}}));rows.sort((a,b)=>b.score-a.score);return json(res,200,{ok:true,engine_version:'V3-SWING-2-4D',updated_at_utc:new Date().toISOString(),market_status:'LIVE_WHEN_UPSTOX_CONNECTED',rows});}catch(e){return json(res,401,{ok:false,error:e.message||'Screener failed',market_status:'UPSTOX_NOT_CONNECTED'});}}