const UPSTOX_BASE='https://api.upstox.com';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(body));}
function cookies(req){const out={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out;}
async function upstox(path,req){const token=cookies(req).upstox_access_token||process.env.UPSTOX_ANALYTICS_TOKEN||process.env.UPSTOX_ACCESS_TOKEN;if(!token)throw new Error('UPSTOX_NOT_CONNECTED');const r=await fetch(UPSTOX_BASE+path,{headers:{Accept:'application/json',Authorization:'Bearer '+token}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('Upstox '+r.status);return d;}
const clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const dateIST=(n=0)=>{const d=new Date(Date.now()+5.5*60*60*1000);d.setUTCDate(d.getUTCDate()-n);return d.toISOString().slice(0,10)};
async function resolve(symbol,req){const d=await upstox('/v2/instruments/search?query='+encodeURIComponent(symbol)+'&exchanges=NSE&segments=EQ&page_number=1&records=30',req);const a=Array.isArray(d?.data)?d.data:[];const x=a.find(r=>r.segment==='NSE_EQ'&&clean(r.trading_symbol)===clean(symbol))||a.find(r=>r.segment==='NSE_EQ');return x?{symbol,instrument_key:x.instrument_key,trading_symbol:x.trading_symbol,name:x.name||x.short_name}:null;}
async function candles(key,unit,interval,fromDays,req){const to=dateIST(0),from=dateIST(fromDays);const d=await upstox('/v3/historical-candle/'+encodeURIComponent(key)+'/'+unit+'/'+interval+'/'+to+'/'+from,req);return Array.isArray(d?.data?.candles)?d.data.candles:[];}
function norm(cs){return cs.map(c=>({t:new Date(c[0]).getTime(),o:+c[1],h:+c[2],l:+c[3],c:+c[4],v:+(c[5]||0)})).filter(x=>x.c>0).sort((a,b)=>a.t-b.t);}
function ema(a,n){if(a.length<n)return null;let e=a.slice(0,n).reduce((s,x)=>s+x,0)/n,k=2/(n+1);for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e;}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al===0?100:100-100/(1+ag/al);}
function atr(a,n=14){if(a.length<n+1)return null;const tr=a.slice(1).map((x,i)=>Math.max(x.h-x.l,Math.abs(x.h-a[i].c),Math.abs(x.l-a[i].c)));return tr.slice(-n).reduce((s,x)=>s+x,0)/n;}
function analyze(day,mins,marketBias='NEUTRAL'){
 if(day.length<55)return{score:0,signal:'WAIT',reason:'Insufficient daily history',setup:'WAIT'};
 const d=day.at(-1),prev=day.at(-2),p20=day.slice(-21,-1),pPrev=day.slice(-22,-2),cl=day.map(x=>x.c),high20=Math.max(...p20.map(x=>x.h)),prevHigh20=pPrev.length?Math.max(...pPrev.map(x=>x.h)):high20,avgv=p20.reduce((s,x)=>s+x.v,0)/p20.length,a=atr(day)||d.c*.02,e20=ema(cl,20),e50=ema(cl,50),rs=rsi(cl),why=[];let score=0;
 const freshBreakout=d.c>high20&&(!prev||prev.c<=prevHigh20),breakout=d.c>high20,volumeSpike=avgv>0&&d.v/avgv>=1.5;
 const emaTouch=d.l<=e20*1.015&&d.c>e20*0.995&&d.c>d.o,closeStrong=d.c>=d.l+(d.h-d.l)*0.6,bounce=emaTouch&&closeStrong&&d.c>e20;
 if(d.c>e20&&e20>e50){score+=20;why.push('trend bullish')}else if(d.c>e20){score+=12;why.push('above EMA20')}else if(d.c<e20&&e20<e50){why.push('trend weak')}else score+=6;
 if(rs>=60&&rs<=72){score+=20;why.push('RSI momentum')}else if(rs>72){score+=12;why.push('strong but extended')}else if(rs>=50){score+=10;why.push('neutral momentum')}else score+=3;
 if(freshBreakout){score+=24;why.push('FRESH BREAKOUT')}else if(breakout){score+=18;why.push('20D BREAKOUT')}else if(bounce){score+=20;why.push('EMA20 BOUNCE')}else if(d.c>Math.max(...p20.slice(-5).map(x=>x.h))){score+=14;why.push('short-term strength')}else score+=4;
 const vr=avgv?d.v/avgv:0;if(volumeSpike&&d.c>d.o){score+=22;why.push('VOLUME SPIKE')}else if(vr>=1.2&&d.c>d.o){score+=14;why.push('volume supportive')}else if(vr>=1){score+=8;why.push('normal volume')}else score+=3;
 const sl=Math.max(d.c-1.2*a,d.c*.97),risk=Math.max(d.c-sl,.01),t1=d.c+risk*1.5,t2=d.c+risk*2.2,t3=d.c+risk*3,rr=(t2-d.c)/risk;if(rr>=2){score+=20;why.push('risk-reward good')}else score+=10;
 if(mins.length>=12){const m=mins.at(-1),mp=mins.slice(-7,-1),mh=Math.max(...mp.map(x=>x.h));if(m.c>mh){score=Math.min(100,score+5);why.push('5m confirmation')}}
 if(marketBias==='BULLISH'){score=Math.min(100,score+5);why.push('NIFTY market filter bullish')}else if(marketBias==='BEARISH'){score=Math.max(0,score-10);why.push('NIFTY market filter bearish')}else if(marketBias==='SIDEWAYS'){score=Math.max(0,score-5);why.push('NIFTY market filter sideways')}
 const rawScore=Math.round(Math.max(0,Math.min(100,score)));
 const setup=freshBreakout||breakout?'BREAKOUT':bounce?'PULLBACK':rawScore>=75?'MOMENTUM':'WATCH';
 const confirmationGate=(freshBreakout||bounce)&&vr>=1.2;
 if(!confirmationGate)score=Math.min(score,74);
 if(vr<1.2)why.push('WAIT: volume below confirmation threshold');
 if(!freshBreakout&&!bounce)why.push('WAIT: no fresh breakout/bounce');
 score=Math.round(Math.max(0,Math.min(100,score)));
 const signal=score>=75?'BUY':score>=55?'WATCH':'WAIT',actionable=signal==='BUY';
 return{score,signal,setup,close:actionable?d.c:null,volume_ratio:+vr.toFixed(2),volume_spike:volumeSpike,breakout,breakout_fresh:freshBreakout,bounce_ema20:bounce,rsi:rs==null?null:+rs.toFixed(1),ema20:+e20.toFixed(2),ema50:+e50.toFixed(2),entry_low:actionable?+(d.c*.998).toFixed(2):null,entry_high:actionable?+(d.c*1.004).toFixed(2):null,sl:actionable?+sl.toFixed(2):null,t1:actionable?+t1.toFixed(2):null,t2:actionable?+t2.toFixed(2):null,t3:actionable?+t3.toFixed(2):null,rr:actionable?'1:2.2':null,atr:+a.toFixed(2),reason:why.join(' + '),holding:'2–4 days'};
}
async function marketContext(req){try{const[nifty,vix]=await Promise.all([candles('NSE_INDEX|Nifty 50','days','1',90,req),candles('NSE_INDEX|India VIX','days','1',30,req)]);const nd=norm(nifty),vx=norm(vix);if(nd.length<55)return{bias:'UNKNOWN',vix:null,reason:'NIFTY history unavailable'};const nc=nd.map(x=>x.c),last=nd.at(-1),e20=ema(nc,20),e50=ema(nc,50);let bias='SIDEWAYS';if(last.c>e20&&e20>e50)bias='BULLISH';else if(last.c<e20&&e20<e50)bias='BEARISH';return{bias,vix:vx.length?vx.at(-1).c:null,nifty:last.c,nifty_ema20:e20,nifty_ema50:e50,reason:'NIFTY EMA20/50 market filter',fii_dii:'VERIFY_LIVE'};}catch(e){return{bias:'UNKNOWN',vix:null,reason:'Market context unavailable',fii_dii:'VERIFY_LIVE'};}}
const DEFAULT_UNIVERSE='RELIANCE,SBIN,HDFCBANK,ICICIBANK,INFY,TCS,AXISBANK,TATASTEEL,MARUTI,BHARTIARTL';
const EXPANDED_UNIVERSE='RELIANCE,SBIN,HDFCBANK,ICICIBANK,INFY,TCS,AXISBANK,TATASTEEL,MARUTI,BHARTIARTL,LT,ITC,KOTAKBANK,BAJFINANCE,ADANIENT,NTPC,POWERGRID,SUNPHARMA,HINDALCO,ONGC';
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{ok:false,error:'GET only'});try{const requested=String(req.query?.symbols||DEFAULT_UNIVERSE).split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);const raw=(requested.join(',')===DEFAULT_UNIVERSE?EXPANDED_UNIVERSE:requested.join(',')).split(',').slice(0,20);const market=await marketContext(req);const resolved=(await Promise.all(raw.map(s=>resolve(s,req)))).filter(Boolean);const rows=await Promise.all(resolved.map(async x=>{try{const[day5,mins]=await Promise.all([candles(x.instrument_key,'days','1',90,req),candles(x.instrument_key,'minutes','5',7,req)]);return{...x,...analyze(norm(day5),norm(mins),market.bias),data_source:'Upstox historical',candle_count:day5.length};}catch(e){return{...x,score:0,signal:'WAIT',setup:'WAIT',reason:e.message||'Data unavailable',data_source:'Unavailable',candle_count:0};}}));rows.sort((a,b)=>b.score-a.score);return json(res,200,{ok:true,engine_version:'V5-Breakout-Bounce-Volume-20',universe_size:raw.length,updated_at_utc:new Date().toISOString(),market_status:'LIVE_WHEN_UPSTOX_CONNECTED',market_context:market,rows});}catch(e){return json(res,401,{ok:false,error:e.message||'Screener failed',market_status:'UPSTOX_NOT_CONNECTED'});}}